CREATE TABLE `ads_merchant_profile` (
  `merchant_id` varchar(128) NOT NULL COMMENT "商家id",
  `pt` date NOT NULL COMMENT "业务日期",
  `user_id` text NULL COMMENT "用户id",
  `merchant_type_name` text NULL COMMENT "商户类型name 1.急速发货商户 2.企业商户 3.认证商户 4.跨境商家 5.个人普通商户 6-品牌方",
  `brand_type_name` text NULL COMMENT "资质类型name -1代表商家是服务商 0.基本信息 1.品牌方 2.经销商 3.市场贸易商 4.扫货商 5.零售百货商",
  `balance_type_name` text NULL COMMENT "结算类型name 0.实时 1.周结 2.半月结 3.月结",
  `mobile` text NULL COMMENT "商家手机号",
  `company_name` text NULL COMMENT "公司名称",
  `license_id` text NULL COMMENT "营业执照编号",
  `is_unconditional_refund` bigint NULL COMMENT "是否支持七天无理由退货 0否 1是",
  `is_invoice` bigint NULL COMMENT "是否支持开具发票 0否 1是",
  `refund_mobile` text NULL COMMENT "退货地址收货人手机号",
  `currency` text NULL COMMENT "币种",
  `contact_name` text NULL COMMENT "联系人姓名",
  `contact_idcard` text NULL COMMENT "联系人身份证号",
  `business_address` text NULL COMMENT "经营商详细地址",
  `send_address` text NULL COMMENT "发货详细地址",
  `refnd_address` text NULL COMMENT "退货地址详细地址",
  `bank_name` text NULL COMMENT "开户行",
  `bank_account` text NULL COMMENT "银行账号",
  `account_type_name` text NULL COMMENT "账户类型name 1.对公 2.对私",
  `poundage_discount` text NULL COMMENT "费率折扣",
  `deposit_amt` double NULL COMMENT "保证金余额元",
  `order_cnt_1d` bigint NULL COMMENT "总订单量-最近1天",
  `order_user_cnt_1d` bigint NULL COMMENT "下单用户量-最近1天",
  `order_gmv_amt_1d` double NULL COMMENT "总gmv金额元-最近1天",
  `pay_order_cnt_1d` bigint NULL COMMENT "支付订单量-最近1天",
  `pay_gmv_amt_1d` double NULL COMMENT "支付gmv金额元-最近1天",
  `trade_success_level1_category_cnt_1d` bigint NULL COMMENT "交易成功一级类目数-最近1天",
  `trade_success_level2_category_cnt_1d` bigint NULL COMMENT "交易成功二级类目数-最近1天",
  `trade_success_level3_category_cnt_1d` bigint NULL COMMENT "交易成功三级类目数-最近1天",
  `trade_success_order_cnt_1d` bigint NULL COMMENT "交易成功订单量-最近1天",
  `pay_success_discount_order_cnt_1d` bigint NULL COMMENT "支付成功优惠单量-最近1天",
  `pay_success_discount_amt_1d` double NULL COMMENT "支付成功优惠金额元-最近1天",
  `trade_success_discount_order_cnt_1d` bigint NULL COMMENT "交易成功优惠单量-最近1天",
  `trade_success_discount_amt_1d` double NULL COMMENT "交易成功优惠金额元-最近1天",
  `cs_ticket_cnt_1d` bigint NULL COMMENT "咨询工单量-最近1天",
  `risk_complaint_order_cnt_1d` bigint NULL COMMENT "风控客诉订单量-最近1天",
  `seller_repay_order_cnt_1d` bigint NULL COMMENT "卖家赔付订单数-最近1天",
  `seller_repay_amt_1d` double NULL COMMENT "卖家赔付金额元-最近1天",
  `entry_audit_duration_hours_1d` double NULL COMMENT "入驻审核平均时效小时-最近1天",
  `deposit_pay_cnt_1d` bigint NULL COMMENT "缴纳保证金次数-最近1天",
  `entry_success_duration_hours_1d` double NULL COMMENT "入驻成功平均总时长小时-最近1天",
  `punish_cnt_1d` bigint NULL COMMENT "处罚次数-最近1天；当前按处罚类申诉记录近似，待补处罚单源表校正",
  `appeal_cnt_1d` bigint NULL COMMENT "申诉次数-最近1天",
  `appeal_success_cnt_1d` bigint NULL COMMENT "申诉成功次数-最近1天",
  `scm_performance_cnt_1d` bigint NULL COMMENT "供应链履约量-最近1天；按outbound_modify_time大于outbound_latest_time统计",
  `return_success_cnt_1d` bigint NULL COMMENT "退货成功量-最近1天",
  `return_cnt_1d` bigint NULL COMMENT "退货量-最近1天",
  `fake_identify_cnt_1d` bigint NULL COMMENT "鉴定为假货量-最近1天",
  `check_unpass_cnt_1d` bigint NULL COMMENT "质检不通过量-最近1天",
  `goods_audit_reject_cnt_1d` bigint NULL COMMENT "商品审核拒绝量-最近1天",
  `goods_online_cnt_1d` bigint NULL COMMENT "上架商品量-最近1天",
  `goods_apply_cnt_1d` bigint NULL COMMENT "商品申请量-最近1天",
  `trade_success_gmv_amt_1d` double NULL COMMENT "交易成功gmv金额元-最近1天",
  `trade_success_user_cnt_1d` bigint NULL COMMENT "交易成功用户量-最近1天",
  `avg_pay_order_amt_1d` double NULL COMMENT "支付成功客单价元-最近1天",
  `order_close_cnt_1d` bigint NULL COMMENT "关闭订单量-最近1天",
  `seller_subsidy_amt_1d` double NULL COMMENT "商家补贴金额元-最近1天",
  `platform_subsidy_amt_1d` double NULL COMMENT "平台补贴金额元-最近1天",
  `ship_timeout_order_cnt_1d` bigint NULL COMMENT "发货超时订单量-最近1天",
  `signed_order_cnt_1d` bigint NULL COMMENT "签收订单量-最近1天",
  `delivery_timeout_order_cnt_1d` bigint NULL COMMENT "签收超预计送达订单量-最近1天",
  `pay_discount_rate_1d` double NULL COMMENT "支付成功优惠金额占支付gmv比例-最近1天",
  `refund_amt_1d` double NULL COMMENT "退款金额元-最近1天",
  `return_success_amt_1d` double NULL COMMENT "退货成功金额元-最近1天",
  `seller_responsible_refund_cnt_1d` bigint NULL COMMENT "卖家责任退货量-最近1天",
  `direct_refund_cnt_1d` bigint NULL COMMENT "直接退款量-最近1天",
  `refund_rate_1d` double NULL COMMENT "退货量占支付订单量比例-最近1天",
  `ticket_reopen_cnt_1d` bigint NULL COMMENT "工单二次开启量-最近1天",
  `ticket_reminder_cnt_1d` bigint NULL COMMENT "催单工单量-最近1天",
  `ticket_close_cnt_1d` bigint NULL COMMENT "关闭工单量-最近1天",
  `avg_ticket_score_1d` double NULL COMMENT "平均工单评价分-最近1天",
  `goods_audit_pass_cnt_1d` bigint NULL COMMENT "商品审核通过量-最近1天"
);
