CREATE TABLE `dim_merchant_df` (
  `user_id` varchar(128) NOT NULL COMMENT "用户id",
  `merchant_id` varchar(128) NOT NULL COMMENT "商家id",
  `merchant_type_code` bigint NOT NULL COMMENT "商户类型code 1.急速发货商户 2.企业商户 3.认证商户 4.跨境商家 5.个人普通商户 6-品牌方",
  `merchant_type_name` varchar(128) NOT NULL COMMENT "商户类型name 1.急速发货商户 2.企业商户 3.认证商户 4.跨境商家 5.个人普通商户 6-品牌方",
  `brand_type_code` bigint NOT NULL COMMENT "资质类型code -1代表商家是服务商 0、商家入驻时填基本信息，还没填资质信息 1.品牌方 2.经销商 3.市场贸易商 4.扫货商 5.零售百货商",
  `brand_type_name` varchar(128) NOT NULL COMMENT "资质类型name -1代表商家是服务商 0、商家入驻时填基本信息，还没填资质信息 1.品牌方 2.经销商 3.市场贸易商 4.扫货商 5.零售百货商",
  `audit_user_list` varchar(512) NOT NULL COMMENT "审批人aclIds，逗号分隔",
  `merchant_apply_status_code` bigint NOT NULL COMMENT "审核状态code，商家提交资料-0，保证金/账单/费率/协议填写审核-100，保证金低于标准，二次审核-110，初审不通过-120，初审通过，等待特批费率/类目运营审核-130，初审完成-140，待法务审核-200，法务审核不通过-210，法务审核通过，商家协议待确认-300，商家协议确认成功，保证金待缴纳-500，保证金转账待审核-520，保证金转账审核不通过-530，商家入驻被驳回-600，保证金转账审核通过，入驻完成-800",
  `merchant_apply_status_name` varchar(255) NOT NULL COMMENT "审核状态name",
  `init_deposit_amt` bigint NOT NULL COMMENT "商户入驻初始保证金元",
  `balance_type_code` bigint NOT NULL COMMENT "结算类型code 0.实时 1.周结 2.半月结 3.月结",
  `balance_type_name` varchar(128) NOT NULL COMMENT "结算类型name 0.实时 1.周结 2.半月结 3.月结",
  `mobile` varchar(64) NOT NULL COMMENT "商家手机号",
  `company_name` varchar(255) NOT NULL COMMENT "公司名称",
  `license_id` varchar(128) NOT NULL COMMENT "营业执照编号",
  `license_period_start` varchar(32) NOT NULL COMMENT "营业执照有效期 开始时间",
  `license_period_end` varchar(32) NOT NULL COMMENT "营业执照有效期 结束时间",
  `company_province` varchar(128) NOT NULL COMMENT "省",
  `company_city` varchar(128) NOT NULL COMMENT "市",
  `company_district` varchar(128) NOT NULL COMMENT "区",
  `company_address` varchar(512) NOT NULL COMMENT "详细地址",
  `corporation_name` varchar(128) NOT NULL COMMENT "法人姓名",
  `corporation_idcard` varchar(128) NOT NULL COMMENT "法人身份证号",
  `corporation_idcard_period_start` varchar(32) NOT NULL COMMENT "法人身份有效期 开始时间",
  `corporation_idcard_period_end` varchar(32) NOT NULL COMMENT "法人身份有效期 结束时间",
  `is_unconditional_refund` bigint NOT NULL COMMENT "是否支持七天无理由退货 0 否 1 是",
  `is_invoice` bigint NOT NULL COMMENT "是否支持开具发票 0否 1是",
  `refund_mobile` varchar(64) NOT NULL COMMENT "退货地址收货人手机号",
  `inviter` varchar(128) NOT NULL COMMENT "入驻邀约人姓名",
  `inviter_mobile` varchar(64) NOT NULL COMMENT "入驻邀约人手机号",
  `currency` varchar(32) NOT NULL COMMENT "币种",
  `ship_model_code` varchar(64) NOT NULL COMMENT "发货模式code 1-集货模式 2-自发货模式",
  `ship_model_name` varchar(128) NOT NULL COMMENT "发货模式name 1-集货模式 2-自发货模式",
  `contact_name` varchar(128) NOT NULL COMMENT "联系人姓名",
  `contact_idcard` varchar(128) NOT NULL COMMENT "联系人身份证号",
  `contact_idcard_period_start` bigint NOT NULL COMMENT "联系人身份有效期 开始时间",
  `contact_idcard_period_end` bigint NOT NULL COMMENT "联系人身份有效期 结束时间",
  `contact_idcard_type` bigint NOT NULL COMMENT "联系人默认大陆身份证，类型包括：100 大陆身份证；105 港澳居民往来内地通行证；106 台湾同胞往来大陆通行证；108 外国人居留证",
  `contact_mobile` varchar(64) NOT NULL COMMENT "联系人手机号",
  `business_province` varchar(128) NOT NULL COMMENT "经营商省地区",
  `business_city` varchar(128) NOT NULL COMMENT "经营商所在城市地区",
  `business_district` varchar(128) NOT NULL COMMENT "经营商街道地区",
  `business_address` varchar(512) NOT NULL COMMENT "经营商详细地址",
  `send_province` varchar(128) NOT NULL COMMENT "发货省",
  `send_city` varchar(128) NOT NULL COMMENT "发货市",
  `send_district` varchar(128) NOT NULL COMMENT "发货区",
  `send_street` varchar(128) NOT NULL COMMENT "退货地址街道",
  `send_address` varchar(512) NOT NULL COMMENT "发货详细地址",
  `refnd_province` varchar(128) NOT NULL COMMENT "退货地址省",
  `refnd_city` varchar(128) NOT NULL COMMENT "退货地址市",
  `refnd_district` varchar(128) NOT NULL COMMENT "退货地址区",
  `refnd_street` varchar(128) NOT NULL COMMENT "退货地址街道",
  `refnd_address` varchar(512) NOT NULL COMMENT "退货地址详细地址",
  `service_version` bigint NOT NULL COMMENT "协议版本",
  `min_poundage` bigint NOT NULL COMMENT "手续费下限",
  `max_poundage` bigint NOT NULL COMMENT "手续费上限",
  `bank_name` varchar(255) NOT NULL COMMENT "开户行",
  `bank_account` varchar(128) NOT NULL COMMENT "银行账号",
  `account_type_code` bigint NOT NULL COMMENT "账户类型code 1.对公 2.对私",
  `account_type_name` varchar(128) NOT NULL COMMENT "账户类型name 1.对公 2.对私",
  `deposit_freeze` bigint NOT NULL COMMENT "冻结保证金",
  `deposit_amt` bigint NOT NULL COMMENT "保证金",
  `poundage_discount` varchar(64) NOT NULL COMMENT "费率折扣",
  `discount_start_time` varchar(19) NOT NULL COMMENT "费率折扣开始时间",
  `discount_end_time` varchar(19) NOT NULL COMMENT "费率折扣结束时间",
  `create_time` varchar(19) NOT NULL COMMENT "添加时间",
  `modify_time` varchar(19) NOT NULL COMMENT "修改时间",
  `pt` date NOT NULL COMMENT "日期分区yyyyMMdd",
  INDEX idx_merchant_id (`merchant_id`) USING INVERTED COMMENT "商家id倒排索引"
) ENGINE=OLAP
DUPLICATE KEY(`user_id`)
COMMENT 'dim-商家域-商家信息表'
PARTITION BY RANGE(`pt`)
(PARTITION p20260521 VALUES [('2026-05-21'), ('2026-05-22')),
PARTITION p20260522 VALUES [('2026-05-22'), ('2026-05-23')),
PARTITION p20260523 VALUES [('2026-05-23'), ('2026-05-24')),
PARTITION p20260524 VALUES [('2026-05-24'), ('2026-05-25')),
PARTITION p20260525 VALUES [('2026-05-25'), ('2026-05-26')))
DISTRIBUTED BY HASH(`merchant_id`) BUCKETS 8
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"min_load_replica_num" = "-1",
"is_being_synced" = "false",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "DAY",
"dynamic_partition.time_zone" = "Asia/Shanghai",
"dynamic_partition.start" = "-3",
"dynamic_partition.end" = "1",
"dynamic_partition.prefix" = "p",
"dynamic_partition.replication_allocation" = "tag.location.default: 1",
"dynamic_partition.buckets" = "8",
"dynamic_partition.create_history_partition" = "true",
"dynamic_partition.history_partition_num" = "3",
"dynamic_partition.hot_partition_num" = "0",
"dynamic_partition.reserved_history_periods" = "NULL",
"dynamic_partition.storage_policy" = "",
"storage_medium" = "hdd",
"storage_format" = "V2",
"inverted_index_storage_format" = "V3",
"light_schema_change" = "true",
"disable_auto_compaction" = "false",
"enable_single_replica_compaction" = "false",
"group_commit_interval_ms" = "10000",
"group_commit_data_bytes" = "134217728"
);