CREATE TABLE `dwm_goods_detail_df` (
  `spu_id` bigint NOT NULL COMMENT "spu ID",
  `spu_name` varchar(255) NOT NULL COMMENT "商品名称",
  `seller_id` varchar(128) NOT NULL COMMENT "spu发布人id",
  `seller_name` varchar(255) NOT NULL COMMENT "spu发布人name",
  `source_type_code` bigint NOT NULL COMMENT "spu来源code",
  `source_type_name` varchar(128) NOT NULL COMMENT "spu来源name 个人卖家 企业卖家",
  `level1_category_code` bigint NOT NULL COMMENT "一级类目code",
  `level1_category_name` varchar(128) NOT NULL COMMENT "一级类目name",
  `level2_category_code` bigint NOT NULL COMMENT "二级类目code",
  `level2_category_name` varchar(128) NOT NULL COMMENT "二级类目name",
  `level3_category_code` bigint NOT NULL COMMENT "三级类目code",
  `level3_category_name` varchar(128) NOT NULL COMMENT "三级类目name",
  `brand_code` bigint NOT NULL COMMENT "品牌code",
  `brand_name` varchar(128) NOT NULL COMMENT "品牌name",
  `fit_code` varchar(128) NOT NULL COMMENT "适用人群code",
  `fit_name` varchar(128) NOT NULL COMMENT "适用人群name",
  `spu_auth_price` bigint NOT NULL COMMENT "发售价分",
  `spu_logo_url` varchar(1024) NOT NULL COMMENT "logo图",
  `spu_video_url` varchar(1024) NOT NULL COMMENT "视频图",
  `article_id` varchar(128) NOT NULL COMMENT "货号",
  `spu_status_code` bigint NOT NULL COMMENT "商品状态code 0.下架 1.上架 2.待提交 3.待审核 4.审核通过",
  `spu_status_name` varchar(128) NOT NULL COMMENT "商品状态name 0.下架 1.上架 2.待提交 3.待审核 4.审核通过",
  `spu_desc` varchar(2048) NOT NULL COMMENT "商品描述",
  `spu_apply_create_time` varchar(19) NOT NULL COMMENT "创建时间",
  `spu_apply_modify_time` varchar(19) NOT NULL COMMENT "变更时间",
  `biz_id` varchar(128) NOT NULL COMMENT "唯一ID",
  `completion_operate_type_code` varchar(128) NOT NULL COMMENT "任务状态code。反馈问题；提交任务；",
  `completion_operate_type_name` varchar(128) NOT NULL COMMENT "任务状态name。反馈问题；提交任务；",
  `is_completion_pass` bigint NOT NULL COMMENT "是否通过",
  `completion_remark` varchar(1024) NOT NULL COMMENT "备注",
  `first_completion_operate_id` varchar(128) NOT NULL COMMENT "首次操作人",
  `first_completion_operate_name` varchar(255) NOT NULL COMMENT "首次操作人name",
  `completion_operate_id` varchar(128) NOT NULL COMMENT "最新操作人",
  `completion_operate_name` varchar(255) NOT NULL COMMENT "最新操作人name",
  `first_completion_operate_time` varchar(19) NOT NULL COMMENT "首次操作时间",
  `completion_operate_time` varchar(19) NOT NULL COMMENT "操作时间",
  `audit_operate_type_code` varchar(128) NOT NULL COMMENT "任务状态code。反馈问题；提交任务；",
  `audit_operate_type_name` varchar(128) NOT NULL COMMENT "任务状态name。反馈问题；提交任务；",
  `is_audit_pass` bigint NOT NULL COMMENT "是否通过",
  `audit_remark` varchar(1024) NOT NULL COMMENT "备注",
  `first_audit_operate_id` varchar(128) NOT NULL COMMENT "首次操作人",
  `first_audit_operate_name` varchar(255) NOT NULL COMMENT "首次操作人name",
  `first_audit_operate_supplier_name` varchar(255) NOT NULL COMMENT "首次操作人供应商名称",
  `audit_operate_id` varchar(128) NOT NULL COMMENT "最新操作人",
  `audit_operate_name` varchar(255) NOT NULL COMMENT "最新操作人name",
  `audit_operate_supplier_name` varchar(255) NOT NULL COMMENT "最新操作人供应商名称",
  `first_audit_operate_time` varchar(19) NOT NULL COMMENT "首次操作时间",
  `audit_operate_time` varchar(19) NOT NULL COMMENT "操作时间",
  `import_task_id` varchar(128) NOT NULL COMMENT "导入任务id",
  `excel_url` varchar(1024) NOT NULL COMMENT "excel存放路径",
  `excel_name` varchar(255) NOT NULL COMMENT "导入excel名称",
  `is_import_pass` bigint NOT NULL COMMENT "导入状态",
  `import_time` varchar(19) NOT NULL COMMENT "导入时间",
  `import_operate_id` varchar(128) NOT NULL COMMENT "操作人id",
  `import_operate_name` varchar(255) NOT NULL COMMENT "操作人name",
  `is_risk_audit_pass` bigint NOT NULL COMMENT "是否风控审核通过",
  `machine_audit_time` varchar(19) NOT NULL COMMENT "机审时间",
  `is_manual` bigint NOT NULL COMMENT "机审是否转人工",
  `first_risk_tag_user_id` varchar(128) NOT NULL COMMENT "首次risk最新审核人ID",
  `first_risk_tag_user_name` varchar(255) NOT NULL COMMENT "首次risk最新审核人name",
  `risk_tag_user_id` varchar(128) NOT NULL COMMENT "risk最新审核人ID",
  `risk_tag_user_name` varchar(255) NOT NULL COMMENT "risk最新审核人名称",
  `risk_operate_supplier_name` varchar(255) NOT NULL COMMENT "risk最新审核人供应商",
  `is_white` varchar(32) NOT NULL COMMENT "是否加白",
  `pt` date NOT NULL COMMENT "业务日期",
  INDEX idx_spu_id (`spu_id`) USING INVERTED COMMENT "spu ID倒排索引",
  INDEX idx_seller_id (`seller_id`) USING INVERTED COMMENT "spu发布人id倒排索引"
) ENGINE=OLAP
DUPLICATE KEY(`spu_id`)
COMMENT 'dwm-商品系统-商品上新全流程-全量表'
PARTITION BY RANGE(`pt`)
(PARTITION p20260521 VALUES [('2026-05-21'), ('2026-05-22')),
PARTITION p20260522 VALUES [('2026-05-22'), ('2026-05-23')),
PARTITION p20260523 VALUES [('2026-05-23'), ('2026-05-24')),
PARTITION p20260524 VALUES [('2026-05-24'), ('2026-05-25')),
PARTITION p20260525 VALUES [('2026-05-25'), ('2026-05-26')))
DISTRIBUTED BY HASH(`spu_id`) BUCKETS 8
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"min_load_replica_num" = "-1",
"is_being_synced" = "false",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "DAY",
"dynamic_partition.time_zone" = "Asia/Shanghai",
"dynamic_partition.start" = "-3",
"dynamic_partition.end" = "1",
"dynamic_partition.prefix" = "p",
"dynamic_partition.replication_allocation" = "tag.location.default: 1",
"dynamic_partition.buckets" = "8",
"dynamic_partition.create_history_partition" = "true",
"dynamic_partition.history_partition_num" = "3",
"dynamic_partition.hot_partition_num" = "0",
"dynamic_partition.reserved_history_periods" = "NULL",
"dynamic_partition.storage_policy" = "",
"storage_medium" = "hdd",
"storage_format" = "V2",
"inverted_index_storage_format" = "V3",
"light_schema_change" = "true",
"disable_auto_compaction" = "false",
"enable_single_replica_compaction" = "false",
"group_commit_interval_ms" = "10000",
"group_commit_data_bytes" = "134217728"
);