CREATE TABLE `dwm_trade_order_detail_di` (
  `order_id` varchar(128) NOT NULL COMMENT "主订单号",
  `sub_order_id` varchar(128) NOT NULL COMMENT "订单号",
  `pt` date NOT NULL COMMENT "业务日期",
  `biz_channel_code` text NULL COMMENT "购买渠道code，海外购，秒杀等",
  `biz_channel_name` text NULL COMMENT "购买渠道名称",
  `biz_code` text NULL COMMENT "垂直行业领域划分code,鞋子，数码等",
  `biz_name` text NULL COMMENT "垂直行业领域划分名称,鞋子，数码等",
  `sub_order_status_code` bigint NULL COMMENT "子订单状态code",
  `sub_order_status_name` text NULL COMMENT "子订单状态名称",
  `buyer_id` text NULL COMMENT "买家ID",
  `buyer_name` text NULL COMMENT "买家昵称",
  `seller_id` text NULL COMMENT "卖家ID",
  `seller_name` text NULL COMMENT "卖家昵称",
  `discount_amt` bigint NULL COMMENT "优惠金额",
  `inventory_id` text NULL COMMENT "库存编号",
  `spu_id` text NULL COMMENT "spuId",
  `sku_id` text NULL COMMENT "skuId",
  `sku_name` text NULL COMMENT "sku名称",
  `sku_price` bigint NULL COMMENT "商品单价分",
  `sku_cnt` bigint NULL COMMENT "商品数量",
  `buyer_note` text NULL COMMENT "买家留言",
  `item_json` text NULL COMMENT "商品信息JSON",
  `close_type_code` bigint NULL COMMENT "关闭类型",
  `close_type_name` text NULL COMMENT "关闭类型名称",
  `close_time` text NULL COMMENT "关闭时间",
  `extra` text NULL COMMENT "拓展信息",
  `product_amt` bigint NULL COMMENT "商品总额分",
  `freight_amt` bigint NULL COMMENT "运费金额分",
  `sku_logo_url` text NULL COMMENT "sku图片地址",
  `seller_note` text NULL COMMENT "卖家留言",
  `seller_address_info` text NULL COMMENT "卖家发货地址",
  `seller_address_back` text NULL COMMENT "卖家寄回地址",
  `seller_info` text NULL COMMENT "商家信息",
  `delivery_deadline_time` text NULL COMMENT "卖家发货截止时间",
  `region` text NULL COMMENT "区域",
  `sub_order_create_time` text NULL COMMENT "子订单创建时间",
  `sub_order_modify_time` text NULL COMMENT "子订单更新时间",
  `address_json` text NULL COMMENT "买家地址信息json",
  `address_province_code` text NULL COMMENT "买家地址-省code",
  `address_province_name` text NULL COMMENT "买家地址-省名称",
  `address_city_code` text NULL COMMENT "买家地址-市code",
  `address_city_name` text NULL COMMENT "买家地址-市名称",
  `address_district_code` text NULL COMMENT "买家地址-区code",
  `address_district_name` text NULL COMMENT "买家地址-区名称",
  `address_street_code` text NULL COMMENT "买家地址-街道code",
  `address_street_name` text NULL COMMENT "买家地址-街道名称",
  `platform_name` text NULL COMMENT "设备来源（平台，安卓，ios）",
  `discount_id` text NULL COMMENT "折扣id",
  `discount_type_code` bigint NULL COMMENT "优惠类型code",
  `discount_type_name` text NULL COMMENT "优惠类型name",
  `discount_rel_id` text NULL COMMENT "优惠方式关联的id，优惠券id,红包账号等",
  `is_use` bigint NULL COMMENT "是否使用1是0否",
  `subsidy_json` text NULL COMMENT "补贴信息json",
  `platform_subsidy_amt` bigint NULL COMMENT "平台补贴金额",
  `seller_subsidy_amt` bigint NULL COMMENT "商家补贴金额",
  `discount_create_time` text NULL COMMENT "折扣创建时间",
  `discount_modify_time` text NULL COMMENT "折扣更新时间",
  `appeal_status_code` bigint NULL COMMENT "商家申诉状态code：0 - 未申诉，1 - 申诉中，2 - 通过，3 - 驳回",
  `appeal_status_name` text NULL COMMENT "商家申诉状态名称",
  `appeal_create_time` text NULL COMMENT "商家申诉创建时间",
  `appeal_modify_time` text NULL COMMENT "商家申诉修改时间",
  `pay_id` text NULL COMMENT "支付号",
  `pay_tool_code` bigint NULL COMMENT "支付方式code，支付宝，微信，银行卡",
  `pay_tool_name` text NULL COMMENT "支付方式名称",
  `pay_type_code` bigint NULL COMMENT "支付类型code，定金，尾款",
  `pay_type_name` text NULL COMMENT "支付类型名称，定金，尾款",
  `pay_status_code` bigint NULL COMMENT "支付状态code",
  `pay_status_name` bigint NULL COMMENT "支付状态name",
  `out_pay_id` text NULL COMMENT "支付单流水号(支付服务生成)",
  `pay_amt` bigint NULL COMMENT "支付金额，分",
  `pay_time` text NULL COMMENT "支付时间",
  `pay_start_time` text NULL COMMENT "支付时间段开始时间",
  `pay_end_time` text NULL COMMENT "支付时间段结束时间",
  `pay_extra` text NULL COMMENT "拓展属性",
  `logistic_id` text NULL COMMENT "平台物流编号",
  `logistic_stage_code` bigint NULL COMMENT "物流阶段code，卖家到仓库，仓库到买家",
  `logistic_stage_name` text NULL COMMENT "物流阶段name",
  `express_type_code` text NULL COMMENT "承运方code",
  `express_type_name` text NULL COMMENT "承运方name",
  `express_id` text NULL COMMENT "三方物流编号",
  `express_status_code` bigint NULL COMMENT "物流状态code",
  `express_status_name` text NULL COMMENT "物流状态name",
  `sender_address` text NULL COMMENT "发货地址",
  `receiver_address` text NULL COMMENT "收货地址",
  `sender_mobile` text NULL COMMENT "发件人手机号",
  `receiver_mobile` text NULL COMMENT "收货人手机号",
  `logistic_extra` text NULL COMMENT "拓展属性",
  `logistic_create_time` text NULL COMMENT "创建时间",
  `logistic_modify_time` text NULL COMMENT "更新时间",
  `handover_time` text NULL COMMENT "交接时间",
  `received_time` text NULL COMMENT "揽收时间",
  `signed_received_time` text NULL COMMENT "签收时间",
  `abnormal_rejection_time` text NULL COMMENT "签收异常-拒收时间",
  `abnormal_lost_time` text NULL COMMENT "签收异常-丢件/废弃时间",
  `refuse_withdraw_time` text NULL COMMENT "拒收回退/转寄时间",
  `refuse_withdraw_signed_time` text NULL COMMENT "拒收回退/转寄-签收时间",
  `equivalent_received_time` text NULL COMMENT "等效揽收时间",
  `sendout_time` text NULL COMMENT "发货时间",
  `in_transit_time` text NULL COMMENT "运输时间",
  `first_expected_arrival_time` text NULL COMMENT "首次预计送达时间",
  `expected_arrival_time` text NULL COMMENT "预计送达时间",
  `relative_signed_received_time` text NULL COMMENT "相对签收时间",
  `delivery_time` text NULL COMMENT "派送时间",
  `spu_name` text NULL COMMENT "spu名称",
  `level1_category_code` bigint NULL COMMENT "一级类目code",
  `level1_category_name` text NULL COMMENT "一级类目name",
  `level2_category_code` bigint NULL COMMENT "二级类目code",
  `level2_category_name` text NULL COMMENT "二级类目name",
  `level3_category_code` bigint NULL COMMENT "三级类目code",
  `level3_category_name` text NULL COMMENT "三级类目name",
  `brand_code` bigint NULL COMMENT "品牌code",
  `brand_name` text NULL COMMENT "品牌name",
  `fit_code` bigint NULL COMMENT "适用人群code",
  `fit_name` text NULL COMMENT "适用人群name",
  `spu_auth_price` bigint NULL COMMENT "spu发售价格",
  `spu_logo_url` text NULL COMMENT "logo图",
  `spu_gif_url` text NULL COMMENT "动图",
  `spu_video_cover_url` text NULL COMMENT "视频图",
  `spu_video_url` text NULL COMMENT "视频图",
  `article_id` text NULL COMMENT "货号",
  `other_article_id` text NULL COMMENT "其他货号",
  `spu_status_code` bigint NULL COMMENT "状态code 0.下架 1.上架 2.待提交 3.待审核 4.审核通过",
  `spu_status_name` text NULL COMMENT "状态名称",
  `spu_desc` text NULL COMMENT "商品描述",
  `is_self` bigint NULL COMMENT "是否自营 0.否 1.是",
  `spu_create_time` text NULL COMMENT "spu创建时间",
  `spu_modify_time` text NULL COMMENT "spu更新时间",
  `sku_size` text NULL COMMENT "properties_json中常用的尺寸",
  `sku_color` text NULL COMMENT "properties_json中常用的颜色",
  `sku_spec` text NULL COMMENT "properties_json中常用的规格",
  INDEX idx_sub_order_id (`sub_order_id`) USING INVERTED COMMENT "子订单号索引",
  INDEX idx_seller_id (`seller_id`) USING INVERTED COMMENT "卖家id索引"
) ENGINE=OLAP
UNIQUE KEY(`order_id`, `sub_order_id`, `pt`)
COMMENT 'dwm-交易域-订单域-明细宽表-增量表'
PARTITION BY RANGE(`pt`)
(PARTITION p20260514 VALUES [('2026-05-14'), ('2026-05-15')),
PARTITION p20260515 VALUES [('2026-05-15'), ('2026-05-16')),
PARTITION p20260516 VALUES [('2026-05-16'), ('2026-05-17')),
PARTITION p20260517 VALUES [('2026-05-17'), ('2026-05-18')),
PARTITION p20260518 VALUES [('2026-05-18'), ('2026-05-19')),
PARTITION p20260519 VALUES [('2026-05-19'), ('2026-05-20')),
PARTITION p20260520 VALUES [('2026-05-20'), ('2026-05-21')),
PARTITION p20260521 VALUES [('2026-05-21'), ('2026-05-22')),
PARTITION p20260522 VALUES [('2026-05-22'), ('2026-05-23')),
PARTITION p20260523 VALUES [('2026-05-23'), ('2026-05-24')),
PARTITION p20260524 VALUES [('2026-05-24'), ('2026-05-25')),
PARTITION p20260525 VALUES [('2026-05-25'), ('2026-05-26')),
PARTITION p20260526 VALUES [('2026-05-26'), ('2026-05-27')),
PARTITION p20260527 VALUES [('2026-05-27'), ('2026-05-28')))
DISTRIBUTED BY HASH(`order_id`) BUCKETS 8
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"min_load_replica_num" = "-1",
"is_being_synced" = "false",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "DAY",
"dynamic_partition.time_zone" = "Etc/UTC",
"dynamic_partition.start" = "-1095",
"dynamic_partition.end" = "3",
"dynamic_partition.prefix" = "p",
"dynamic_partition.replication_allocation" = "tag.location.default: 1",
"dynamic_partition.buckets" = "8",
"dynamic_partition.create_history_partition" = "true",
"dynamic_partition.history_partition_num" = "10",
"dynamic_partition.hot_partition_num" = "0",
"dynamic_partition.reserved_history_periods" = "NULL",
"dynamic_partition.storage_policy" = "",
"storage_medium" = "hdd",
"storage_format" = "V2",
"inverted_index_storage_format" = "V3",
"enable_unique_key_merge_on_write" = "true",
"light_schema_change" = "true",
"disable_auto_compaction" = "false",
"enable_single_replica_compaction" = "false",
"group_commit_interval_ms" = "10000",
"group_commit_data_bytes" = "134217728",
"enable_mow_light_delete" = "false"
);