CREATE TABLE `dwm_coupon_detail_di` (
  `coupon_id` varchar(128) NOT NULL COMMENT "券编号",
  `user_id` varchar(128) NOT NULL COMMENT "用户id",
  `suit_owner_code` bigint NOT NULL COMMENT "适用方code",
  `suit_owner_name` varchar(255) NOT NULL COMMENT "适用方name",
  `template_id` varchar(128) NOT NULL COMMENT "优惠券模板编号",
  `template_title` varchar(255) NOT NULL COMMENT "标题",
  `activity_id` varchar(128) NOT NULL COMMENT "活动id",
  `coupon_amt` bigint NOT NULL COMMENT "优惠金额",
  `discount_way_code` bigint NOT NULL COMMENT "优惠方式code",
  `discount_way_name` varchar(128) NOT NULL COMMENT "优惠方式name",
  `found_type_code` bigint NOT NULL COMMENT "款项code",
  `found_type_name` varchar(128) NOT NULL COMMENT "款项name",
  `coupon_start_time` varchar(19) NOT NULL COMMENT "开始时间",
  `coupon_expire_time` varchar(19) NOT NULL COMMENT "过期时间",
  `coupon_send_status_code` bigint NOT NULL COMMENT "状态code",
  `coupon_send_status_name` bigint NOT NULL COMMENT "状态name",
  `threshold` bigint NOT NULL COMMENT "门槛",
  `send_source_name` varchar(128) NOT NULL COMMENT "推送来源",
  `coupon_content` varchar(1024) NOT NULL COMMENT "优惠券信息",
  `coupon_create_time` varchar(19) NOT NULL COMMENT "优惠券创建时间",
  `coupon_modify_time` varchar(19) NOT NULL COMMENT "优惠券更新时间",
  `is_receive` bigint NOT NULL COMMENT "是否抢到优惠券",
  `snap_create_time` varchar(19) NOT NULL COMMENT "抢券创建时间",
  `snap_modify_time` varchar(19) NOT NULL COMMENT "抢券变更时间",
  `coupon_refund_id` varchar(128) NOT NULL COMMENT "优惠券退回编号",
  `refund_time` varchar(19) NOT NULL COMMENT "优惠券退回时间",
  `allowance_amt` varchar(64) NOT NULL COMMENT "津贴金额",
  `seller_id` varchar(128) NOT NULL COMMENT "津贴商家id",
  `seller_name` varchar(255) NOT NULL COMMENT "津贴商家name",
  `allowance_create_time` varchar(19) NOT NULL COMMENT "创建时间",
  `allowance_modify_time` varchar(19) NOT NULL COMMENT "变更时间",
  `template_createtor_id` varchar(128) NOT NULL COMMENT "优惠券创建人id",
  `template_createtor_name` varchar(255) NOT NULL COMMENT "优惠券创建人name",
  `template_remark` varchar(1024) NOT NULL COMMENT "优惠券备注信息",
  `is_voucher` bigint NOT NULL COMMENT "是否代金券",
  `template_create_time` varchar(19) NOT NULL COMMENT "优惠券创建时间",
  `template_modify_time` varchar(19) NOT NULL COMMENT "变更时间",
  `template_valid_dur` bigint NOT NULL COMMENT "模板有效期间，天",
  `activity_name` varchar(255) NOT NULL COMMENT "优惠券活动name",
  `activity_start_time` varchar(19) NOT NULL COMMENT "优惠券活动开始时间",
  `activity_expire_time` varchar(19) NOT NULL COMMENT "优惠券活动结束时间",
  `activity_createtor_id` varchar(128) NOT NULL COMMENT "优惠券活动创建人id",
  `activity_createtor_name` varchar(255) NOT NULL COMMENT "优惠券活动创建人name",
  `activity_create_time` varchar(19) NOT NULL COMMENT "优惠券活动创建时间",
  `activity_modify_time` varchar(19) NOT NULL COMMENT "优惠券活动变更时间",
  `pt` date NOT NULL COMMENT "业务日期",
  INDEX idx_coupon_id (`coupon_id`) USING INVERTED COMMENT "券编号倒排索引",
  INDEX idx_seller_id (`seller_id`) USING INVERTED COMMENT "津贴商家id倒排索引"
) ENGINE=OLAP
DUPLICATE KEY(`coupon_id`)
COMMENT 'dwm-优惠券域-明细表-增量表'
PARTITION BY RANGE(`pt`)
(PARTITION p20260514 VALUES [('2026-05-14'), ('2026-05-15')),
PARTITION p20260515 VALUES [('2026-05-15'), ('2026-05-16')),
PARTITION p20260516 VALUES [('2026-05-16'), ('2026-05-17')),
PARTITION p20260517 VALUES [('2026-05-17'), ('2026-05-18')),
PARTITION p20260518 VALUES [('2026-05-18'), ('2026-05-19')),
PARTITION p20260519 VALUES [('2026-05-19'), ('2026-05-20')),
PARTITION p20260520 VALUES [('2026-05-20'), ('2026-05-21')),
PARTITION p20260521 VALUES [('2026-05-21'), ('2026-05-22')),
PARTITION p20260522 VALUES [('2026-05-22'), ('2026-05-23')),
PARTITION p20260523 VALUES [('2026-05-23'), ('2026-05-24')),
PARTITION p20260524 VALUES [('2026-05-24'), ('2026-05-25')),
PARTITION p20260525 VALUES [('2026-05-25'), ('2026-05-26')),
PARTITION p20260526 VALUES [('2026-05-26'), ('2026-05-27')),
PARTITION p20260527 VALUES [('2026-05-27'), ('2026-05-28')))
DISTRIBUTED BY HASH(`coupon_id`) BUCKETS 8
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"min_load_replica_num" = "-1",
"is_being_synced" = "false",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "DAY",
"dynamic_partition.time_zone" = "Asia/Shanghai",
"dynamic_partition.start" = "-1095",
"dynamic_partition.end" = "3",
"dynamic_partition.prefix" = "p",
"dynamic_partition.replication_allocation" = "tag.location.default: 1",
"dynamic_partition.buckets" = "8",
"dynamic_partition.create_history_partition" = "true",
"dynamic_partition.history_partition_num" = "10",
"dynamic_partition.hot_partition_num" = "0",
"dynamic_partition.reserved_history_periods" = "NULL",
"dynamic_partition.storage_policy" = "",
"storage_medium" = "hdd",
"storage_format" = "V2",
"inverted_index_storage_format" = "V3",
"light_schema_change" = "true",
"disable_auto_compaction" = "false",
"enable_single_replica_compaction" = "false",
"group_commit_interval_ms" = "10000",
"group_commit_data_bytes" = "134217728"
);
