CREATE TABLE `dwm_scm_detail_di` (
  `inbound_id` varchar(128) NOT NULL COMMENT "主键",
  `inbound_header_id` varchar(128) NOT NULL COMMENT "主库单头表id",
  `inbound_express_id` varchar(128) NOT NULL COMMENT "入库运单号",
  `inbound_express_type_code` varchar(128) NOT NULL COMMENT "物流商编号",
  `inbound_express_type_name` varchar(255) NOT NULL COMMENT "物流商名称",
  `is_valid_status` bigint NOT NULL COMMENT "是否有效状态",
  `unique_id` varchar(128) NOT NULL COMMENT "唯一码P码",
  `inbound_status_code` bigint NOT NULL COMMENT "wms入库单状态code1已入库，2运输中，3快递接收中",
  `inbound_status_name` varchar(255) NOT NULL COMMENT "wms入库单状态name 1已入库，2运输中，3快递接收中",
  `spu_id` varchar(128) NOT NULL COMMENT "商品spuid",
  `sku_id` varchar(128) NOT NULL COMMENT "商品skuid",
  `spu_name` varchar(255) NOT NULL COMMENT "spu名称",
  `level1_category_code` bigint NOT NULL COMMENT "一级类目code",
  `level1_category_name` varchar(255) NOT NULL COMMENT "一级类目name",
  `level2_category_code` bigint NOT NULL COMMENT "二级类目code",
  `level2_category_name` varchar(255) NOT NULL COMMENT "二级类目name",
  `level3_category_code` bigint NOT NULL COMMENT "三级类目code",
  `level3_category_name` varchar(255) NOT NULL COMMENT "三级类目name",
  `brand_code` bigint NOT NULL COMMENT "品牌code",
  `brand_name` varchar(255) NOT NULL COMMENT "品牌name",
  `article_id` varchar(128) NOT NULL COMMENT "货号",
  `inbound_cnt` bigint NOT NULL COMMENT "入库数量",
  `inbound_create_time` varchar(19) NOT NULL COMMENT "入库创建时间",
  `inbound_modify_time` varchar(19) NOT NULL COMMENT "入库变更时间",
  `inbound_receive_time` varchar(19) NOT NULL COMMENT "入库接收时间",
  `is_check` bigint NOT NULL COMMENT "是否需要查验 1 正常 0 免鉴别",
  `warehouse_id` varchar(128) NOT NULL COMMENT "仓库id",
  `warhouse_name` varchar(255) NOT NULL COMMENT "仓库name",
  `online_time` varchar(19) NOT NULL COMMENT "上架时间",
  `dispatch_bill_id` varchar(128) NOT NULL COMMENT "发货单号",
  `seller_id` varchar(128) NOT NULL COMMENT "卖家id-个人卖家",
  `seller_name` varchar(255) NOT NULL COMMENT "卖家姓名-个人卖家",
  `seller_nick_name` varchar(255) NOT NULL COMMENT "卖家姓名-个人卖家",
  `seller_address` varchar(1024) NOT NULL COMMENT "卖家地址",
  `deliver_time` varchar(19) NOT NULL COMMENT "发货时间",
  `is_cross` bigint NOT NULL COMMENT "是否跨境1 是",
  `is_express` bigint NOT NULL COMMENT "是否极速 1是",
  `inbound_header_remark` varchar(1024) NOT NULL COMMENT "备注",
  `expect_start_time` varchar(19) NOT NULL COMMENT "预计到货时间",
  `inbound_header_type_code` bigint NOT NULL COMMENT "入库单表头code1 销售入货单2退货入货单",
  `inbound_header_type_name` varchar(255) NOT NULL COMMENT "入库单表头name1 销售入货单2退货入货单",
  `merchant_id` varchar(128) NOT NULL COMMENT "商家id-企业卖家",
  `merchant_name` varchar(255) NOT NULL COMMENT "商家名称-企业卖家",
  `latest_inbound_time` varchar(19) NOT NULL COMMENT "预计最晚到仓时间",
  `sorting_id` varchar(128) NOT NULL COMMENT "分拣id",
  `sorting_operator_id` varchar(128) NOT NULL COMMENT "分拣人ID",
  `sorting_operator_name` varchar(255) NOT NULL COMMENT "分拣人名称",
  `sorting_group_code` varchar(128) NOT NULL COMMENT "供应商编码-外包厂商",
  `sorting_group_name` varchar(255) NOT NULL COMMENT "供应商名称-外包厂商",
  `sorting_salary` bigint NOT NULL COMMENT "薪资-每天",
  `sorting_attend_start_time` varchar(19) NOT NULL COMMENT "考勤开始时间例如9:00",
  `sorting_attend_end_time` varchar(19) NOT NULL COMMENT "考勤结束时间例如18:00",
  `sorting_attend_days` bigint NOT NULL COMMENT "每月要求出勤天数，例如26",
  `sorting_source_code` bigint NOT NULL COMMENT "分拣来源1国内2海外",
  `sorting_source_name` varchar(255) NOT NULL COMMENT "分拣来源1国内2海外",
  `sorting_status_code` bigint NOT NULL COMMENT "分拣状态code 1已接收2已完成",
  `sorting_status_name` varchar(255) NOT NULL COMMENT "分拣状态name 1已接收2已完成",
  `sorting_remark` varchar(1024) NOT NULL COMMENT "分拣备注",
  `sorting_warhouse_id` varchar(128) NOT NULL COMMENT "分拣仓库名",
  `sorting_create_time` varchar(19) NOT NULL COMMENT "分拣时间",
  `sorting_modify_time` varchar(19) NOT NULL COMMENT "分拣完成时间",
  `sorting_station_id` varchar(128) NOT NULL COMMENT "分拣工位",
  `sorting_production_line_code` varchar(128) NOT NULL COMMENT "分拣生产产线code",
  `sorting_production_line_name` varchar(255) NOT NULL COMMENT "分拣生产产线",
  `check_id` varchar(128) NOT NULL COMMENT "质检id",
  `check_task_id` varchar(128) NOT NULL COMMENT "任务id",
  `check_status_code` bigint NOT NULL COMMENT "质检状态：1：质检通过；2：有瑕疵；3：质检不通过",
  `check_status_name` varchar(255) NOT NULL COMMENT "质检状态name：1：质检通过；2：有瑕疵；3：质检不通过",
  `unpass_type_code` bigint NOT NULL COMMENT "不通过方式code；1：无；2：普通操作；3：管理员不通过（已通过后操作不通过）",
  `unpass_type_name` varchar(255) NOT NULL COMMENT "不通过方式name；1：无；2：普通操作；3：管理员不通过（已通过后操作不通过）",
  `check_operator_id` varchar(128) NOT NULL COMMENT "审核人员",
  `check_operator_name` varchar(255) NOT NULL COMMENT "审核人员",
  `check_group_code` varchar(128) NOT NULL COMMENT "供应商编码-外包厂商",
  `check_group_name` varchar(255) NOT NULL COMMENT "供应商名称-外包厂商",
  `check_salary` bigint NOT NULL COMMENT "薪资-每天",
  `check_attend_start_time` varchar(19) NOT NULL COMMENT "考勤开始时间例如9:00",
  `check_attend_end_time` varchar(19) NOT NULL COMMENT "考勤结束时间例如18:00",
  `check_attend_days` bigint NOT NULL COMMENT "每月要求出勤天数，例如26",
  `check_create_time` varchar(19) NOT NULL COMMENT "创建时间",
  `check_modify_time` varchar(19) NOT NULL COMMENT "修改时间",
  `check_type_code` bigint NOT NULL COMMENT "质检类型 0常规质检 1二次质检（现货转寄存）",
  `check_type_name` varchar(255) NOT NULL COMMENT "质检类型 0常规质检 1二次质检（现货转寄存）",
  `photo_cnt` bigint NOT NULL COMMENT "质检图片数量",
  `check_cnt` bigint NOT NULL COMMENT "审核次数",
  `biz_type_code` bigint NOT NULL COMMENT "业务类型code 0:小仓库;1企业；2个人",
  `biz_type_name` varchar(255) NOT NULL COMMENT "业务类型name 0:小仓库;1企业；2个人",
  `check_source_type_code` bigint NOT NULL COMMENT "来源类型  1:原有 2:新的（需要选择瑕疵选项）",
  `check_source_type_name` varchar(255) NOT NULL COMMENT "来源类型  1:原有 2:新的（需要选择瑕疵选项）",
  `check_reason_id` varchar(128) NOT NULL COMMENT "id",
  `check_reason_name` varchar(255) NOT NULL COMMENT "原因类别名称",
  `apply_type_code` bigint NOT NULL COMMENT "原因适用类型；1：拒收；2：鉴定;3：质检",
  `apply_type_name` varchar(255) NOT NULL COMMENT "原因适用类型；1：拒收；2：鉴定;3：质检",
  `first_check_task_id` varchar(128) NOT NULL COMMENT "首次质检任务编号",
  `first_check_is_operate_pass` bigint NOT NULL COMMENT "首次质检结果,不通过=0,通过=1",
  `first_check_operate_remark` varchar(1024) NOT NULL COMMENT "首次质检备注",
  `first_check_operator_id` varchar(128) NOT NULL COMMENT "首次质检操作人id",
  `first_check_operator_name` varchar(255) NOT NULL COMMENT "首次质检操作人名称",
  `first_check_group_code` varchar(128) NOT NULL COMMENT "首次质检供应商编码-外包厂商",
  `first_check_group_name` varchar(255) NOT NULL COMMENT "首次质检供应商名称-外包厂商",
  `first_check_reason_id` varchar(128) NOT NULL COMMENT "首次质检原因id",
  `first_check_reason_name` varchar(255) NOT NULL COMMENT "首次质检原因类别名称",
  `first_check_apply_type_code` bigint NOT NULL COMMENT "首次质检原因适用类型；1：拒收；2：鉴定;3：质检",
  `first_check_apply_type_name` varchar(255) NOT NULL COMMENT "首次质检原因适用类型；1：拒收；2：鉴定;3：质检",
  `identify_id` varchar(128) NOT NULL COMMENT "鉴定id",
  `identify_task_id` varchar(128) NOT NULL COMMENT "任务id",
  `is_identify_online` bigint NOT NULL COMMENT "是否线上坚定",
  `is_identify` bigint NOT NULL COMMENT "是否鉴定 0-未鉴定 1-已鉴定",
  `identify_result_code` bigint NOT NULL COMMENT "鉴定结果 0-初始状态 1-鉴定为真 2-鉴定为假 3-待补图 4-无法鉴定 5-已撤销 6-已挂起",
  `identify_result_name` varchar(255) NOT NULL COMMENT "鉴定结果 0-初始状态 1-鉴定为真 2-鉴定为假 3-待补图 4-无法鉴定 5-已撤销 6-已挂起",
  `identifier_id` varchar(128) NOT NULL COMMENT "鉴定师id",
  `identifier_name` varchar(255) NOT NULL COMMENT "鉴定师name",
  `identify_content` varchar(1024) NOT NULL COMMENT "鉴定原因",
  `photo_time` varchar(19) NOT NULL COMMENT "拍照时间",
  `identify_create_time` varchar(19) NOT NULL COMMENT "创建时间",
  `identify_modify_time` varchar(19) NOT NULL COMMENT "更新时间",
  `first_identify_task_id` varchar(128) NOT NULL COMMENT "任务编号",
  `first_identify_pass_type_code` bigint NOT NULL COMMENT "鉴定结果 0-初始状态 1-鉴定为真 2-鉴定为假 3-待补图 4-无法鉴定 5-已撤销 6-已挂起",
  `first_identify_pass_type_name` varchar(255) NOT NULL COMMENT "鉴定结果 0-初始状态 1-鉴定为真 2-鉴定为假 3-待补图 4-无法鉴定 5-已撤销 6-已挂起",
  `first_identify_operate_remark` varchar(1024) NOT NULL COMMENT "备注",
  `first_identify_operator_id` varchar(128) NOT NULL COMMENT "操作人id",
  `first_identify_operator_name` varchar(255) NOT NULL COMMENT "操作人名称",
  `outbound_id` varchar(128) NOT NULL COMMENT "出库单id",
  `outbound_type_code` bigint NOT NULL COMMENT "出库单据类型1揽货中2运输中3已签收",
  `asoutbound_type_name` varchar(255) NOT NULL COMMENT "出库单据类型1揽货中2运输中3已签收",
  `outbound_create_time` varchar(19) NOT NULL COMMENT "出库单明细创建时间",
  `outbound_modify_time` varchar(19) NOT NULL COMMENT "出库单明细变更时间",
  `outbound_express_type_code` varchar(128) NOT NULL COMMENT "出库单承运商类型",
  `outbound_express_type_name` varchar(255) NOT NULL COMMENT "物流商名称",
  `outbound_express_id` varchar(128) NOT NULL COMMENT "出库单运单号",
  `promise_type_code` bigint NOT NULL COMMENT "承诺类型:0:普通，1：次日达，2：当日达",
  `promise_type_name` varchar(255) NOT NULL COMMENT "承诺类型:0:普通，1：次日达，2：当日达",
  `outbound_latest_time` varchar(19) NOT NULL COMMENT "最晚出库时间",
  `operator_id` varchar(128) NOT NULL COMMENT "出库交接操作人",
  `operator_name` varchar(255) NOT NULL COMMENT "出库交接操作人",
  `outbound_group_code` varchar(128) NOT NULL COMMENT "供应商编码-外包厂商",
  `outbound_group_name` varchar(255) NOT NULL COMMENT "供应商名称-外包厂商",
  `outbound_salary` bigint NOT NULL COMMENT "薪资-每天",
  `outbound_attend_start_time` varchar(19) NOT NULL COMMENT "考勤开始时间例如9:00",
  `outbound_attend_end_time` varchar(19) NOT NULL COMMENT "考勤结束时间例如18:00",
  `outbound_attend_days` bigint NOT NULL COMMENT "每月要求出勤天数，例如26",
  `pt` date NOT NULL COMMENT "业务日期",
  INDEX idx_inbound_id (`inbound_id`) USING INVERTED COMMENT "主键倒排索引"
) ENGINE=OLAP
DUPLICATE KEY(`inbound_id`)
COMMENT 'dwm-供应链域-全流程明细表-增量表'
PARTITION BY RANGE(`pt`)
(PARTITION p20260514 VALUES [('2026-05-14'), ('2026-05-15')),
PARTITION p20260515 VALUES [('2026-05-15'), ('2026-05-16')),
PARTITION p20260516 VALUES [('2026-05-16'), ('2026-05-17')),
PARTITION p20260517 VALUES [('2026-05-17'), ('2026-05-18')),
PARTITION p20260518 VALUES [('2026-05-18'), ('2026-05-19')),
PARTITION p20260519 VALUES [('2026-05-19'), ('2026-05-20')),
PARTITION p20260520 VALUES [('2026-05-20'), ('2026-05-21')),
PARTITION p20260521 VALUES [('2026-05-21'), ('2026-05-22')),
PARTITION p20260522 VALUES [('2026-05-22'), ('2026-05-23')),
PARTITION p20260523 VALUES [('2026-05-23'), ('2026-05-24')),
PARTITION p20260524 VALUES [('2026-05-24'), ('2026-05-25')),
PARTITION p20260525 VALUES [('2026-05-25'), ('2026-05-26')),
PARTITION p20260526 VALUES [('2026-05-26'), ('2026-05-27')),
PARTITION p20260527 VALUES [('2026-05-27'), ('2026-05-28')))
DISTRIBUTED BY HASH(`inbound_id`) BUCKETS 8
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"min_load_replica_num" = "-1",
"is_being_synced" = "false",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "DAY",
"dynamic_partition.time_zone" = "Asia/Shanghai",
"dynamic_partition.start" = "-1095",
"dynamic_partition.end" = "3",
"dynamic_partition.prefix" = "p",
"dynamic_partition.replication_allocation" = "tag.location.default: 1",
"dynamic_partition.buckets" = "8",
"dynamic_partition.create_history_partition" = "true",
"dynamic_partition.history_partition_num" = "10",
"dynamic_partition.hot_partition_num" = "0",
"dynamic_partition.reserved_history_periods" = "NULL",
"dynamic_partition.storage_policy" = "",
"storage_medium" = "hdd",
"storage_format" = "V2",
"inverted_index_storage_format" = "V3",
"light_schema_change" = "true",
"disable_auto_compaction" = "false",
"enable_single_replica_compaction" = "false",
"group_commit_interval_ms" = "10000",
"group_commit_data_bytes" = "134217728"
);