CREATE TABLE `dwm_cs_ticket_detail_di` (
  `ticket_id` varchar(128) NOT NULL COMMENT "工单编号",
  `pt` date NOT NULL COMMENT "业务日期",
  `ticket_title` text NULL COMMENT "工单标题",
  `session_id` text NULL COMMENT "会话id",
  `call_id` text NULL COMMENT "通话id",
  `ticket_source_code` text NULL COMMENT "末级来源id",
  `priority_code` bigint NULL COMMENT "工单等级类型code",
  `priority_name` text NULL COMMENT "工单等级类型name，普通、加急",
  `ticket_type_code` text NULL COMMENT "工单类型code，存储最后级别的分类id",
  `user_type_code` bigint NULL COMMENT "客户身份，0买家、1卖家",
  `user_type_name` text NULL COMMENT "客户身份，买家、卖家",
  `start_operator_id` text NULL COMMENT "工单发起人",
  `assignee_operator_id` text NULL COMMENT "工单跟进人",
  `assignee_group_id` text NULL COMMENT "处理组id",
  `is_reopen` bigint NULL COMMENT "是否二次开启 0否 1时",
  `is_forward` bigint NULL COMMENT "是否流转 0 否 1 是",
  `responsible_type_code` bigint NULL COMMENT "责任方code，1买家 2卖家 3客户",
  `responsible_type_name` text NULL COMMENT "责任方name，买家 卖家 客户",
  `close_time` text NULL COMMENT "工单完成时间",
  `follow_time` text NULL COMMENT "工单相应时间，第一次消息回复消息",
  `chat_time` text NULL COMMENT "工单会话",
  `evaluate_time` text NULL COMMENT "工单评价会话",
  `cancel_time` text NULL COMMENT "工单取消时间",
  `ticket_status_code` bigint NULL COMMENT "工单状态code",
  `ticket_status_name` text NULL COMMENT "工单状态name",
  `spu_id` text NULL COMMENT "商品id",
  `is_reminder` bigint NULL COMMENT "是否催单 0 否 1 是",
  `reminder_cnt` bigint NULL COMMENT "催单次数",
  `evaluation_status_code` bigint NULL COMMENT "评价状态code，0未邀评 1买家邀评 2卖家已邀评 3 卖家买家已邀评",
  `evaluation_status_name` text NULL COMMENT "评价状态name",
  `ticket_score` bigint NULL COMMENT "工单评价分数",
  `ticket_create_time` text NULL COMMENT "工单创建时间",
  `ticket_modify_time` text NULL COMMENT "工单更新时间",
  `order_id` text NULL COMMENT "订单号",
  `sub_order_id` text NULL COMMENT "子订单号",
  `buyer_id` text NULL COMMENT "买家id",
  `buyer_name` text NULL COMMENT "买家用户昵称",
  `buyer_real_name` text NULL COMMENT "买家用户姓名",
  `buyer_mobile` text NULL COMMENT "买家用户手机",
  `seller_type_code` bigint NULL COMMENT "商户类型code 0.个人vip商户 1.急速发货商户 2.企业商户 3.认证商户 4.跨境商家  5.个人普通商户",
  `seller_type_name` text NULL COMMENT "商户类型name",
  `seller_express_id` text NULL COMMENT "卖家运单号，指卖家发往平台的运单",
  `seller_express_type_code` bigint NULL COMMENT "卖家物流类型code",
  `seller_express_type_name` text NULL COMMENT "卖家物流类型name",
  `buyer_express_id` text NULL COMMENT "买家运单号，指平台发往用户的运单",
  `buyer_express_type_code` bigint NULL COMMENT "买家物流类型code",
  `buyer_express_type_name` text NULL COMMENT "买家物流类型name",
  `seller_id` text NULL COMMENT "卖家用户id",
  `seller_name` text NULL COMMENT "卖家用户昵称",
  `seller_real_name` text NULL COMMENT "卖家用户姓名",
  `seller_mobile` text NULL COMMENT "卖家联系方式",
  `ticket_content` text NULL COMMENT "留言信息，富文本",
  `msg_content_list` text NULL COMMENT "对话list",
  `attachment_url_list` text NULL COMMENT "附件list",
  `check_result` text NULL COMMENT "质检结果,通过、未通过",
  `check_remark` text NULL COMMENT "质检备注",
  `level1_source_code` bigint NULL COMMENT "一级来源code",
  `level1_source_name` text NULL COMMENT "一级来源名称",
  `level2_source_code` bigint NULL COMMENT "二级来源code",
  `level2_source_name` text NULL COMMENT "二级来源名称",
  `level3_source_code` bigint NULL COMMENT "三级来源code",
  `level3_source_name` text NULL COMMENT "三级来源名称",
  `level1_type_code` bigint NULL COMMENT "工单一级类型id",
  `level1_type_name` text NULL COMMENT "工单一级类型",
  `level2_type_code` bigint NULL COMMENT "工单二级类型id",
  `level2_type_name` text NULL COMMENT "工单二级类型",
  `level3_type_code` bigint NULL COMMENT "工单三级类型id",
  `level3_type_name` text NULL COMMENT "工单三级类型",
  `operator_name` text NULL COMMENT "工单操作人用户名",
  `real_name` text NULL COMMENT "真实姓名",
  `email` text NULL COMMENT "邮箱地址",
  `mobile` text NULL COMMENT "手机号",
  `operator_type_code` bigint NULL COMMENT "员工类型 1全渠道员工 2呼叫中心员工 3即时通讯员工 4工单员工 5外呼员工",
  `operator_type_name` text NULL COMMENT "员工类型 1全渠道员工 2呼叫中心员工 3即时通讯员工 4工单员工 5外呼员工",
  `spu_name` text NULL COMMENT "spu名称",
  `level1_category_code` bigint NULL COMMENT "一级类目code",
  `level1_category_name` text NULL COMMENT "一级类目name",
  `level2_category_code` bigint NULL COMMENT "二级类目code",
  `level2_category_name` text NULL COMMENT "二级类目name",
  `level3_category_code` bigint NULL COMMENT "三级类目code",
  `level3_category_name` text NULL COMMENT "三级类目name",
  `brand_code` bigint NULL COMMENT "品牌code",
  `brand_name` text NULL COMMENT "品牌name",
  INDEX idx_ticket_id (`ticket_id`) USING INVERTED COMMENT "工单编号索引",
  INDEX idx_seller_id (`seller_id`) USING INVERTED COMMENT "卖家id索引"
) ENGINE=OLAP
UNIQUE KEY(`ticket_id`, `pt`)
COMMENT 'dwm-客服域-工单域-明细宽表-增量表'
PARTITION BY RANGE(`pt`)
(PARTITION p20260514 VALUES [('2026-05-14'), ('2026-05-15')),
PARTITION p20260515 VALUES [('2026-05-15'), ('2026-05-16')),
PARTITION p20260516 VALUES [('2026-05-16'), ('2026-05-17')),
PARTITION p20260517 VALUES [('2026-05-17'), ('2026-05-18')),
PARTITION p20260518 VALUES [('2026-05-18'), ('2026-05-19')),
PARTITION p20260519 VALUES [('2026-05-19'), ('2026-05-20')),
PARTITION p20260520 VALUES [('2026-05-20'), ('2026-05-21')),
PARTITION p20260521 VALUES [('2026-05-21'), ('2026-05-22')),
PARTITION p20260522 VALUES [('2026-05-22'), ('2026-05-23')),
PARTITION p20260523 VALUES [('2026-05-23'), ('2026-05-24')),
PARTITION p20260524 VALUES [('2026-05-24'), ('2026-05-25')),
PARTITION p20260525 VALUES [('2026-05-25'), ('2026-05-26')),
PARTITION p20260526 VALUES [('2026-05-26'), ('2026-05-27')),
PARTITION p20260527 VALUES [('2026-05-27'), ('2026-05-28')))
DISTRIBUTED BY HASH(`ticket_id`) BUCKETS 8
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"min_load_replica_num" = "-1",
"is_being_synced" = "false",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "DAY",
"dynamic_partition.time_zone" = "Etc/UTC",
"dynamic_partition.start" = "-1095",
"dynamic_partition.end" = "3",
"dynamic_partition.prefix" = "p",
"dynamic_partition.replication_allocation" = "tag.location.default: 1",
"dynamic_partition.buckets" = "8",
"dynamic_partition.create_history_partition" = "true",
"dynamic_partition.history_partition_num" = "10",
"dynamic_partition.hot_partition_num" = "0",
"dynamic_partition.reserved_history_periods" = "NULL",
"dynamic_partition.storage_policy" = "",
"storage_medium" = "hdd",
"storage_format" = "V2",
"inverted_index_storage_format" = "V3",
"enable_unique_key_merge_on_write" = "true",
"light_schema_change" = "true",
"disable_auto_compaction" = "false",
"enable_single_replica_compaction" = "false",
"group_commit_interval_ms" = "10000",
"group_commit_data_bytes" = "134217728",
"enable_mow_light_delete" = "false"
);