CREATE TABLE `dwm_trade_refund_detail_di` (
  `refund_id` varchar(128) NOT NULL COMMENT "退货单号",
  `pt` date NOT NULL COMMENT "业务日期",
  `order_id` text NULL COMMENT "主订单编号",
  `sub_order_id` text NULL COMMENT "子订单号",
  `biz_type_code` text NULL COMMENT "产品维度划分code",
  `biz_type_name` text NULL COMMENT "产品维度划分name",
  `biz_channel_code` text NULL COMMENT "购买渠道code",
  `biz_channel_name` text NULL COMMENT "购买渠道name",
  `buyer_id` text NULL COMMENT "买家id",
  `buyer_name` text NULL COMMENT "买家昵称",
  `seller_id` text NULL COMMENT "卖家id",
  `seller_name` text NULL COMMENT "卖家昵称",
  `refund_type_code` bigint NULL COMMENT "退款类型code",
  `refund_type_name` text NULL COMMENT "退款类型name",
  `refund_status_code` bigint NULL COMMENT "退款状态code",
  `refund_status_name` text NULL COMMENT "退款状态name",
  `refund_reason` text NULL COMMENT "退款原因",
  `sku_id` text NULL COMMENT "skuid",
  `sku_title` text NULL COMMENT "商品标题",
  `sku_price` bigint NULL COMMENT "商品单价",
  `sku_count` bigint NULL COMMENT "商品数量",
  `item_json` text NULL COMMENT "商品信息json",
  `buyer_note` text NULL COMMENT "买家退款留言",
  `refund_extra` text NULL COMMENT "拓展属性",
  `refund_close_type_code` bigint NULL COMMENT "退换货单关闭类型code",
  `refund_close_type_name` text NULL COMMENT "退换货单关闭类型name",
  `refund_close_time` text NULL COMMENT "关闭时间",
  `refund_amt_status_code` bigint NULL COMMENT "退款状态code",
  `refund_amt_status_name` text NULL COMMENT "退款状态name",
  `seller_type_code` bigint NULL COMMENT "卖家类型code",
  `seller_type_name` text NULL COMMENT "卖家类型name",
  `operator_id` text NULL COMMENT "操作人id",
  `operator_type_code` bigint NULL COMMENT "操作人类型code",
  `operator_type_name` text NULL COMMENT "操作人类型name",
  `exchange_status_code` bigint NULL COMMENT "换货状态code",
  `exchange_status_name` text NULL COMMENT "换货状态name",
  `refund_create_time` text NULL COMMENT "创建时间",
  `refund_modify_time` text NULL COMMENT "更新时间",
  `bill_from_code` bigint NULL COMMENT "金额来源code",
  `bill_from_name` text NULL COMMENT "金额来源name",
  `pay_tool_code` bigint NULL COMMENT "支付方式code",
  `pay_tool_name` text NULL COMMENT "支付方式name",
  `pay_status_code` bigint NULL COMMENT "支付状态code",
  `pay_status_name` text NULL COMMENT "支付状态name",
  `out_pay_id` text NULL COMMENT "支付单流水号",
  `pay_amt` bigint NULL COMMENT "支付金额",
  `pay_extra` text NULL COMMENT "支付拓展属性",
  `pay_create_time` text NULL COMMENT "支付创建时间",
  `pay_modify_time` text NULL COMMENT "支付更新时间",
  `logistic_id` text NULL COMMENT "全局唯一物流编号",
  `logistic_stage_code` bigint NULL COMMENT "物流阶段code",
  `logistic_stage_name` text NULL COMMENT "物流阶段name",
  `express_type_code` text NULL COMMENT "承运方code",
  `express_type_name` text NULL COMMENT "承运方name",
  `express_id` text NULL COMMENT "物流编号",
  `express_status_code` bigint NULL COMMENT "物流状态code",
  `express_status_name` text NULL COMMENT "物流状态name",
  `sender_address` text NULL COMMENT "发货地址",
  `receiver_address` text NULL COMMENT "收货地址",
  `sender_mobile` text NULL COMMENT "发件人手机号",
  `receiver_mobile` text NULL COMMENT "收货人手机号",
  `logistic_extra` text NULL COMMENT "物流拓展属性",
  `logistic_create_time` text NULL COMMENT "物流创建时间",
  `logistic_modify_time` text NULL COMMENT "物流更新时间",
  `discount_id` text NULL COMMENT "优惠券编号",
  `discount_type_code` bigint NULL COMMENT "优惠类型code",
  `discount_type_name` text NULL COMMENT "优惠类型name",
  `process_status_code` bigint NULL COMMENT "使用状态code",
  `process_status_name` text NULL COMMENT "使用状态name",
  `refund_discount_amt` bigint NULL COMMENT "优惠金额",
  `discount_extra` text NULL COMMENT "优惠券拓展属性",
  `discount_create_time` text NULL COMMENT "优惠券创建时间",
  `discount_modify_time` text NULL COMMENT "优惠券更新时间",
  `spu_name` text NULL COMMENT "spu名称",
  `level1_category_code` bigint NULL COMMENT "一级类目code",
  `level1_category_name` text NULL COMMENT "一级类目name",
  `level2_category_code` bigint NULL COMMENT "二级类目code",
  `level2_category_name` text NULL COMMENT "二级类目name",
  `level3_category_code` bigint NULL COMMENT "三级类目code",
  `level3_category_name` text NULL COMMENT "三级类目name",
  `brand_code` bigint NULL COMMENT "品牌code",
  `brand_name` text NULL COMMENT "品牌name",
  `fit_code` bigint NULL COMMENT "适用人群code",
  `fit_name` text NULL COMMENT "适用人群name",
  `spu_auth_price` bigint NULL COMMENT "spu发售价格",
  `spu_logo_url` text NULL COMMENT "logo图",
  `spu_gif_url` text NULL COMMENT "动图",
  `spu_video_cover_url` text NULL COMMENT "视频图",
  `spu_video_url` text NULL COMMENT "视频URL",
  `article_id` text NULL COMMENT "货号",
  `other_article_id` text NULL COMMENT "其他货号",
  `spu_status_code` bigint NULL COMMENT "状态code",
  `spu_status_name` text NULL COMMENT "状态名称",
  `spu_desc` text NULL COMMENT "商品描述",
  `is_self` bigint NULL COMMENT "是否自营",
  `spu_create_time` text NULL COMMENT "spu创建时间",
  `spu_modify_time` text NULL COMMENT "spu更新时间",
  `sku_size` text NULL COMMENT "尺寸",
  `sku_color` text NULL COMMENT "颜色",
  `sku_spec` text NULL COMMENT "规格",
  `refund_desc` text NULL COMMENT "描述",
  `responsible_party_code` bigint NULL COMMENT "责任方code",
  `responsible_party_name` text NULL COMMENT "责任方name",
  `is_buyer_available` bigint NULL COMMENT "买家是否可用",
  `is_customer_available` bigint NULL COMMENT "客服是否可用",
  `is_all_order_biz_type_available` bigint NULL COMMENT "是否适用全部订单类型",
  `is_direct_refund` bigint NULL COMMENT "是否直接退款",
  `buyer_mobile` text NULL COMMENT "买家手机号",
  `buyer_target_id` text NULL COMMENT "收货人对应buyer_id",
  `logistic_amt` bigint NULL COMMENT "物流金额",
  INDEX idx_refund_id (`refund_id`) USING INVERTED COMMENT "退货单号索引",
  INDEX idx_seller_id (`seller_id`) USING INVERTED COMMENT "卖家id索引"
) ENGINE=OLAP
UNIQUE KEY(`refund_id`, `pt`)
COMMENT 'dwm-交易域-退货域-明细宽表-增量表'
PARTITION BY RANGE(`pt`)
(PARTITION p20260514 VALUES [('2026-05-14'), ('2026-05-15')),
PARTITION p20260515 VALUES [('2026-05-15'), ('2026-05-16')),
PARTITION p20260516 VALUES [('2026-05-16'), ('2026-05-17')),
PARTITION p20260517 VALUES [('2026-05-17'), ('2026-05-18')),
PARTITION p20260518 VALUES [('2026-05-18'), ('2026-05-19')),
PARTITION p20260519 VALUES [('2026-05-19'), ('2026-05-20')),
PARTITION p20260520 VALUES [('2026-05-20'), ('2026-05-21')),
PARTITION p20260521 VALUES [('2026-05-21'), ('2026-05-22')),
PARTITION p20260522 VALUES [('2026-05-22'), ('2026-05-23')),
PARTITION p20260523 VALUES [('2026-05-23'), ('2026-05-24')),
PARTITION p20260524 VALUES [('2026-05-24'), ('2026-05-25')),
PARTITION p20260525 VALUES [('2026-05-25'), ('2026-05-26')),
PARTITION p20260526 VALUES [('2026-05-26'), ('2026-05-27')),
PARTITION p20260527 VALUES [('2026-05-27'), ('2026-05-28')))
DISTRIBUTED BY HASH(`refund_id`) BUCKETS 8
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"min_load_replica_num" = "-1",
"is_being_synced" = "false",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "DAY",
"dynamic_partition.time_zone" = "Etc/UTC",
"dynamic_partition.start" = "-1095",
"dynamic_partition.end" = "3",
"dynamic_partition.prefix" = "p",
"dynamic_partition.replication_allocation" = "tag.location.default: 1",
"dynamic_partition.buckets" = "8",
"dynamic_partition.create_history_partition" = "true",
"dynamic_partition.history_partition_num" = "10",
"dynamic_partition.hot_partition_num" = "0",
"dynamic_partition.reserved_history_periods" = "NULL",
"dynamic_partition.storage_policy" = "",
"storage_medium" = "hdd",
"storage_format" = "V2",
"inverted_index_storage_format" = "V3",
"enable_unique_key_merge_on_write" = "true",
"light_schema_change" = "true",
"disable_auto_compaction" = "false",
"enable_single_replica_compaction" = "false",
"group_commit_interval_ms" = "10000",
"group_commit_data_bytes" = "134217728",
"enable_mow_light_delete" = "false"
);