CREATE TABLE `dwm_cs_repay_detail_df` (
  `bill_id` varchar(128) NOT NULL COMMENT "赔付单号，PF190827160812345",
  `pt` date NOT NULL COMMENT "业务日期",
  `cause_id` text NULL COMMENT "赔付原因",
  `order_id` text NULL COMMENT "订单号",
  `is_return` bigint NULL COMMENT "是否已退货 0否 1是",
  `repay_amt` bigint NULL COMMENT "支付金额",
  `ticket_id` text NULL COMMENT "工单号",
  `buyer_id` text NULL COMMENT "赔付买家id",
  `buyer_name` text NULL COMMENT "赔付买家用户名",
  `seller_id` text NULL COMMENT "赔付卖家用户id",
  `seller_name` text NULL COMMENT "赔付卖家用户名",
  `content` text NULL COMMENT "备注",
  `reject_content` text NULL COMMENT "驳回原因",
  `repay_status_code` bigint NULL COMMENT "状态code，1审批中，2已驳回，3审批完成, 4已取消",
  `repay_status_name` text NULL COMMENT "状态名称",
  `creator_id` text NULL COMMENT "建立人员",
  `create_time` text NULL COMMENT "系统时间",
  `modifier_id` text NULL COMMENT "修改人员",
  `modify_time` text NULL COMMENT "修改时间",
  `pay_status_code` bigint NULL COMMENT "到账状态code 1打款中 2打款失败 3打款成功",
  `pay_status_name` text NULL COMMENT "到账状态name",
  `pay_way_code` bigint NULL COMMENT "赔款方式code 1优惠券2现金3语兴好物币",
  `pay_way_name` text NULL COMMENT "赔款方式name",
  `sub_order_id` text NULL COMMENT "子订单号",
  `express_id` text NULL COMMENT "运单号",
  `pay_account` text NULL COMMENT "支付账户",
  `process_id` text NULL COMMENT "流程ID",
  `reason_code` bigint NULL COMMENT "赔付原因",
  `coupon_type_code` bigint NULL COMMENT "优惠券类型code 1满减券 2包邮券",
  `coupon_type_name` text NULL COMMENT "优惠券类型name",
  `coupon_rule_a` bigint NULL COMMENT "满多少元",
  `coupon_rule_b` bigint NULL COMMENT "减多少元",
  `coupon_time_limit` text NULL COMMENT "优惠券使用期限，格式：2019-08-25,2019-08-28",
  `coupon_id` text NULL COMMENT "优惠券id",
  `activity_id` text NULL COMMENT "活动id",
  `level1_reason_code` bigint NULL COMMENT "一级理赔理由code",
  `level1_reason_name` text NULL COMMENT "一级理赔理由name",
  `level2_reason_code` bigint NULL COMMENT "二级理赔理由id",
  `level2_reason_name` text NULL COMMENT "二级理赔理由name",
  `level3_reason_code` bigint NULL COMMENT "三级理赔理由id",
  `level3_reason_name` text NULL COMMENT "三级理赔理由name",
  INDEX idx_bill_id (`bill_id`) USING INVERTED COMMENT "赔付单号索引",
  INDEX idx_seller_id (`seller_id`) USING INVERTED COMMENT "卖家id索引"
) ENGINE=OLAP
UNIQUE KEY(`bill_id`, `pt`)
COMMENT 'dwm-客服域-理赔全流程表-全量表'
PARTITION BY RANGE(`pt`)
(PARTITION p20260521 VALUES [('2026-05-21'), ('2026-05-22')),
PARTITION p20260522 VALUES [('2026-05-22'), ('2026-05-23')),
PARTITION p20260523 VALUES [('2026-05-23'), ('2026-05-24')),
PARTITION p20260524 VALUES [('2026-05-24'), ('2026-05-25')),
PARTITION p20260525 VALUES [('2026-05-25'), ('2026-05-26')),
PARTITION p20260526 VALUES [('2026-05-26'), ('2026-05-27')),
PARTITION p20260527 VALUES [('2026-05-27'), ('2026-05-28')))
DISTRIBUTED BY HASH(`bill_id`) BUCKETS 8
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"min_load_replica_num" = "-1",
"is_being_synced" = "false",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "DAY",
"dynamic_partition.time_zone" = "Etc/UTC",
"dynamic_partition.start" = "-3",
"dynamic_partition.end" = "3",
"dynamic_partition.prefix" = "p",
"dynamic_partition.replication_allocation" = "tag.location.default: 1",
"dynamic_partition.buckets" = "8",
"dynamic_partition.create_history_partition" = "true",
"dynamic_partition.history_partition_num" = "3",
"dynamic_partition.hot_partition_num" = "0",
"dynamic_partition.reserved_history_periods" = "NULL",
"dynamic_partition.storage_policy" = "",
"storage_medium" = "hdd",
"storage_format" = "V2",
"inverted_index_storage_format" = "V3",
"enable_unique_key_merge_on_write" = "true",
"light_schema_change" = "true",
"disable_auto_compaction" = "false",
"enable_single_replica_compaction" = "false",
"group_commit_interval_ms" = "10000",
"group_commit_data_bytes" = "134217728",
"enable_mow_light_delete" = "false"
);
